Scaffold a new controller using kubebuilder
kyma-project/eventing-manager pull request #6
Opened 2023-06-01 13:10 UTC by mfaizanse

**Description**

Changes proposed in this pull request:

- Scaffold a new controller using kubebuilder
- [Checklist](https://github.com/kyma-project/eventing-manager/issues/4#issuecomment-1571904737)

**Related issue(s)**

- https://github.com/kyma-project/eventing-manager/issues/4

2023-06-01 13:11 UTC, mfaizanse commented
/test all

2023-06-01 13:17 UTC, mfaizanse commented
/test all

2023-06-07 14:29 UTC, friedrichwilken requested changes

2023-06-07 14:29 UTC, friedrichwilken commented on api/v1alpha1/eventing_types.go
> +// Eventing is the Schema for the eventings API
this way it becomes clearer that the decorators belong to `Eventing`.

```suggestion
// Eventing is the Schema for the eventing API.
//+kubebuilder:object:root=true
//+kubebuilder:subresource:status
```

2023-06-07 14:29 UTC, friedrichwilken commented on api/v1alpha1/eventing_types.go
> +// EventingList contains a list of Eventing
```suggestion

// EventingList contains a list of Eventing.
//+kubebuilder:object:root=true
```

2023-06-07 14:29 UTC, friedrichwilken commented on api/v1alpha1/eventing_types.go
> +// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
begone
```suggestion
```

2023-06-07 14:29 UTC, friedrichwilken commented on go.mod
> +go 1.19
```suggestion
go 1.20
```

2023-06-07 14:47 UTC, mfaizanse commented on api/v1alpha1/eventing_types.go
> +// EventingList contains a list of Eventing
updated

2023-06-07 14:47 UTC, mfaizanse commented on README.md
> +You’ll need a Kubernetes cluster to run against. You can use [KIND](https://sigs.k8s.io/kind) to get a local cluster for testing, or run against a remote cluster.
updated

2023-06-07 14:50 UTC, friedrichwilken approved these changes

2023-06-07 14:51 UTC, merged